variables:
    GIT_DEPTH: "1"

stages:
    - develop_build
    - release_build
    - prepare_develop_debs
    - prepare_release_debs

develop_build:
    tags:
        - Runner-Stretch
    stage: develop_build
    except:
      refs:
        - stretch
    script:
        - echo "deb http://mil-internal-apt:8080/mirror-debian_20190909/ stretch main contrib non-free" > /etc/apt/sources.list
        - curl -fsSL http://mil-internal-apt:8080/mil_internal_apt.gpg | apt-key add -
        - apt-get update
        - apt-get install -y -qq --no-install-recommends build-essential devscripts
        - apt-get build-dep ./ -y
        - dpkg-buildpackage -us -uc -b
        - mv ../*.buildinfo .
        - mv ../*.changes .
        - mv ../*.deb .
    artifacts:
        name: "${CI_PROJECT_NAME}"
        paths:
        - ./*.buildinfo
        - ./*.changes
        - ./*.deb

release_build:
    tags:
        - Runner-Stretch
    stage: release_build
    only:
      refs:
        - stretch
    script:
        - echo "deb http://mil-internal-apt:8080/mirror-debian_20190909/ stretch main contrib non-free" > /etc/apt/sources.list
        - curl -fsSL http://mil-internal-apt:8080/mil_internal_apt.gpg | apt-key add -
        - apt-get update
        - apt-get install -y -qq --no-install-recommends build-essential devscripts
        - apt-get build-dep ./ -y
        - dpkg-buildpackage -us -uc -b
        - mv ../*.buildinfo .
        - mv ../*.changes .
        - mv ../*.deb .
    artifacts:
        name: "${CI_PROJECT_NAME}"
        paths:
        - ./*.buildinfo
        - ./*.changes
        - ./*.deb

prepare_develop_debs:
    tags:
        - Runner-Stretch
    stage: prepare_develop_debs
    only:
      refs:
        - stretch-develop
    dependencies:
        - develop_build
    when: manual
    script:
        - mkdir -p /cache/stretch/develop/
        - cp *.deb /cache/stretch/develop/
        - ls /cache/stretch/develop/

prepare_release_debs:
    tags:
        - Runner-Stretch
    stage: prepare_release_debs
    only:
      refs:
        - stretch
    dependencies:
        - release_build
    when: manual
    script:
        - mkdir -p /cache/stretch/release/
        - cp *.deb /cache/stretch/release/
        - ls /cache/stretch/release/
